cppalliance/decimal

include/boost/decimal/decimal32.hpp
Prints in scientific format and always with 2 digits in the exponent portion.
=> Make operator<< templated as in 3.2.11

include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/from_chars_integer_impl.hpp, include/boost/decimal/detail/from_chars_result.hpp, include/boost/decimal/detail/parser.hpp, test/Jamfile, test/test_decimal32_stream.cpp
=> Implement decimal32 Operator>>

include/boost/decimal/common_math.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/type_traits.hpp, test/Jamfile, test/test_decimal_quantum.cpp
Implement `samequantum` and `samequantumd32` from Section 3.6.4
=> Decimal32 samequantum

include/boost/decimal/common_math.hpp, include/boost/decimal/decimal32.hpp, test/test_decimal_quantum.cpp
=> Decimal32 quantexp

include/boost/decimal.hpp, include/boost/decimal/cstdlib.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/from_chars_integer_impl.hpp, include/boost/decimal/detail/parser.hpp, include/boost/decimal/detail/utilities.hpp, test/Jamfile, test/test_strtod.cpp
=> Decimal32 strtod

include/boost/decimal.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/config.hpp, include/boost/decimal/fenv.hpp, test/Jamfile, test/test_fenv.cpp
=> Implement <cfenv> additions

include/boost/decimal/decimal32.hpp, test/test_decimal32.cpp
@ckormanyos hopefully this will fix your issue with construction of values ~2^23
=> Fix construction of values equal to number of bits

include/boost/decimal.hpp, include/boost/decimal/literals.hpp, test/Jamfile, test/test_literals.cpp
=> Add decimal32 literals

include/boost/decimal/decimal32.hpp
@ckormanyos 
I figured this would be easier than describing in review comments.
- Changed everything to trailing return type
- Removed forward declaration of `decimal32`. It's in the fwd header
- Add constexpr construction of constants.
- Prefer decimal32 Construction with integers of floating. The floats are only constexpr at >= C++20, and the construction involves decomposing them into an integer and an exponent. E.g decimal32(5, -1) is better than decimal32(0.5)
- Removed redundant casts sonar lint complained about
- 4 space indents
Let me know if you have any questions or points you want to discuss (like preferring the trailing return type).
=> Editorial changes to cmath

include/boost/decimal.hpp, include/boost/decimal/cmath.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/cmath/fmax.hpp, include/boost/decimal/detail/cmath/fmin.hpp, include/boost/decimal/detail/cmath/isgreater.hpp, include/boost/decimal/detail/cmath/isless.hpp, include/boost/decimal/detail/cmath/isunordered.hpp, include/boost/decimal/detail/emulated128.hpp, include/boost/decimal/fwd.hpp, test/Jamfile, test/test_decimal32_cmath.cpp
=> Add fmax, fmin and remaining comparison functions

include/boost/decimal/cmath.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/cmath/trunc.hpp, test/test_decimal32_cmath.cpp
=> Add floor, ceil, and trunk

include/boost/decimal/common_math.hpp, include/boost/decimal/decimal32.hpp, test/test_decimal32_cmath.cpp
=> Frexp10, scalbn, and scalbln

include/boost/decimal/cmath.hpp, include/boost/decimal/decimal32.hpp, test/test_decimal32_cmath.cpp
=> Add Copysign for decimal32

include/boost/decimal/cmath.hpp, include/boost/decimal/decimal32.hpp, test/test_decimal32_cmath.cpp
=> Add trivial fma impl

include/boost/decimal/cmath.hpp, include/boost/decimal/numbers.hpp, test/Jamfile, test/test_constants.cpp
=> Add C++20 standard constants

include/boost/decimal/cmath.hpp, include/boost/decimal/decimal32.hpp, test/test_decimal32_cmath.cpp
=> Implement modfd32

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/remainder.hpp, test/test_decimal32_cmath.cpp
=> Implement generic remainder

include/boost/decimal/cmath.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/cmath/fabs.hpp, include/boost/decimal/detail/cmath/frexp.hpp, include/boost/decimal/detail/cmath/ilogb.hpp, include/boost/decimal/detail/cmath/ldexp.hpp, include/boost/decimal/detail/cmath/pow.hpp, test/cover/make_gcov_01_generic.gmk, test/cover/make_gcov_02_files.gmk, test/cover/make_gcov_04_rules.gmk, test/test_frexp_ldexp.cpp
The purpose of this PR is to complete `frexp` and `ldexp`, add tests, more coverage and handle arguments zero, inf and NaN.
=> Progress on ldexp/frexp

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/fdim.hpp, test/test_decimal32_cmath.cpp
=> Implement generic fdim

include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/apply_sign.hpp
=> Refactor add to allow for future Integer use

include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/apply_sign.hpp, include/boost/decimal/detail/type_traits.hpp
=> Refactor sub to allow for future integer use

include/boost/decimal/decimal32.hpp
=> Refactor mul impl

include/boost/decimal/common_math.hpp, include/boost/decimal/cstdlib.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/apply_sign.hpp, include/boost/decimal/detail/bit_cast.hpp, include/boost/decimal/detail/emulated128.hpp, include/boost/decimal/detail/fast_float/compute_float32.hpp, include/boost/decimal/detail/fast_float/compute_float64.hpp, include/boost/decimal/detail/from_chars_integer_impl.hpp, include/boost/decimal/detail/from_chars_result.hpp, include/boost/decimal/detail/integer_search_trees.hpp, include/boost/decimal/detail/parser.hpp, include/boost/decimal/detail/power_tables.hpp, include/boost/decimal/detail/ryu/generic_128.hpp, include/boost/decimal/detail/ryu/ryu_generic_128.hpp, include/boost/decimal/detail/utilities.hpp, test/quick.cpp, test/tidy/make_tidy_03_flags.gmk
Let's see if this can be done simply enough? This PR is a prototype for #102.
=> Progress trailing return type

include/boost/decimal/decimal32.hpp, test/test_decimal32_cmath.cpp
=> Implement real FMA

test/test_edges_and_behave.cpp
The purpose of this PR is to hit more hard-to-reach lines and try to cover more edge cases.
=> Cover edges and hard-to-reach lines

include/boost/decimal/cmath.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/cmath/abs.hpp, include/boost/decimal/detail/cmath/ceil.hpp, include/boost/decimal/detail/cmath/floor.hpp, include/boost/decimal/detail/cmath/fmod.hpp, include/boost/decimal/detail/cmath/fpclassify.hpp, include/boost/decimal/detail/cmath/isfinite.hpp, include/boost/decimal/detail/cmath/modf.hpp, include/boost/decimal/detail/cmath/trunc.hpp, test/test_decimal32.cpp, test/test_decimal32_cmath.cpp
=> Make additional cmath functions generic instead of friends

include/boost/decimal/cmath.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/cmath/hypot.hpp, include/boost/decimal/detail/cmath/sqrt.hpp, test/test_decimal32_cmath.cpp
=> Implement sqrt and hypot

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/promotion.hpp, test/Jamfile, test/test_promotion.cpp
=> Implement promotion system

include/boost/decimal/detail/cmath/fpclassify.hpp, include/boost/decimal/detail/cmath/log.hpp, include/boost/decimal/numbers.hpp, test/test_log.cpp
The purpose of this PR is to improve/update `log()`.
- The non-normal arguments are corrected (hoefully)
- and tolerances have been improved.
- Corresponding test cases are included.
=> Update and improve log impl

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/frexp10.hpp, include/boost/decimal/detail/cmath/nearbyint.hpp, include/boost/decimal/detail/cmath/rint.hpp, test/test_decimal32_cmath.cpp
Closes: #151 
Closes: #152 
Closes: #153 
Closes: #154
=> rint, lrint, llrint, and nearbyint

include/boost/decimal.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/hash.hpp, test/test_decimal32.cpp
=> Add hash function specialization

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/round.hpp, test/test_decimal32_cmath.cpp
Closes: #160 
Closes: #161 
Closes: #162
=> Round, lround, and llround

include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/attributes.hpp, include/boost/decimal/detail/cmath/frexp.hpp, include/boost/decimal/detail/cmath/ldexp.hpp, include/boost/decimal/detail/ryu/ryu_generic_128.hpp, test/test_decimal32.cpp, test/test_decimal_quantum.cpp
Refactor the naming of the remaining masks
Closes: #100
=> Make attributes template constants

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/next.hpp, test/test_decimal32_cmath.cpp
=> Implement nextafter and nexttoward

include/boost/decimal/decimal32.hpp, test/random_decimal32_comp.cpp, test/random_decimal32_math.cpp, test/roundtrip_decimal32.cpp, test/test_decimal32.cpp, test/test_decimal32_cmath.cpp, test/test_decimal32_stream.cpp, test/test_decimal_quantum.cpp, test/test_float_conversion.cpp, test/test_strtod.cpp
=> Improve decimal32 coverage

include/boost/decimal/detail/cmath/cos.hpp, include/boost/decimal/detail/cmath/sin.hpp, include/boost/decimal/detail/fast_float/compute_float32.hpp, include/boost/decimal/detail/from_chars_integer_impl.hpp, include/boost/decimal/detail/parser.hpp, test/test_decimal32_cmath.cpp, test/test_float_conversion.cpp
=> Improve <cmath> coverage

include/boost/decimal.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/type_traits.hpp, include/boost/decimal/fwd.hpp, test/Jamfile, test/test_decimal64_basis.cpp
=> Add basis for decimal64

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/comparison.hpp, include/boost/decimal/detail/normalize.hpp, test/random_decimal32_comp.cpp, test/test_decimal32.cpp, test/test_decimal64_basis.cpp
Closes: #181 
Closes: #182 
Closes: #183 
Closes: #184 
Closes: #185 
Closes: #186
=> Decimal64 comparisons

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/to_integral.hpp, test/Jamfile, test/random_decimal64_comp.cpp
=> Conversion to and from integral types

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/random_decimal32_comp.cpp, test/random_decimal64_comp.cpp
=> Decimal64 spaceship operator

.gitignore, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/cmath/fpclassify.hpp, include/boost/decimal/detail/parser.hpp, include/boost/decimal/detail/to_float.hpp, test/Jamfile, test/roundtrip_decimal64.cpp
=> Conversion from and to floating point types for decimal64

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/check_non_finite.hpp, include/boost/decimal/detail/fenv_rounding.hpp, include/boost/decimal/detail/normalize.hpp, include/boost/decimal/detail/shrink_significand.hpp, include/boost/decimal/detail/to_integral.hpp, test/Jamfile, test/random_decimal64_math.cpp, test/test_decimal32.cpp
=> Decimal64 addition

include/boost/decimal/decimal64.hpp, test/random_decimal64_math.cpp
=> Decimal64 Subtraction

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/random_decimal32_math.cpp, test/random_decimal64_math.cpp
=> Cover sub Integer - decimal type

include/boost/decimal/decimal64.hpp
=> Add std::numeric_limits specialization for decimal64

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/acosh.hpp, include/boost/decimal/detail/cmath/sqrt.hpp, test/test_acosh.cpp
The purpose of this PR is to implement and test `acosh`.
=> Preliminary implementation and test acosh

doc/decimal/decimal32.adoc, doc/decimal/decimal64.adoc, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/random_decimal64_math.cpp
=> Operator* for decimal64

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/random_decimal32_math.cpp, test/random_decimal64_math.cpp
Closes: #225 
Closes: #226 
Closes: #227 
Closes: #228
=> Division and modulo for decimal64

include/boost/decimal/decimal64.hpp, test/test_decimal32_cmath.cpp
=> Add Increment and decrement operators to decimal64

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/random_decimal32_math.cpp, test/random_decimal64_math.cpp
=> Add compound assignment operators for Decimal64

include/boost/decimal/cstdlib.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/literals.hpp, test/test_literals.cpp, test/test_strtod.cpp
=> Add strtod and literals to decimal64

include/boost/decimal/detail/fast_float/compute_float64.hpp, test/test_float_conversion.cpp
Remove pessimization for inexact rounding that does not affect decimal to decimal roundtrip 
Closes: #242
=> Fix conversion of inexact rounding

.github/workflows/ci.yml
Also add buffer to timeout time.
=> Reduce GHA runtime

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/random_mixed_decimal_comp.cpp, test/roundtrip_decimal32.cpp, test/roundtrip_decimal64.cpp
=> Add conversion between decimal types

include/boost/decimal/hash.hpp
=> Add decimal64 hash function

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/mixed_decimal_arithmetic.hpp, include/boost/decimal/detail/promotion.hpp, include/boost/decimal/detail/to_decimal.hpp, test/Jamfile, test/random_mixed_decimal_math.cpp, test/test_promotion.cpp
=> Implement mixed decimal arithmetic operators

include/boost/decimal.hpp, include/boost/decimal/cfloat.hpp, include/boost/decimal/cmath.hpp, include/boost/decimal/fwd.hpp
=> Add cmath and cfloat macros

include/boost/decimal/detail/io.hpp, test/roundtrip_decimal32.cpp, test/roundtrip_decimal64.cpp, test/test_decimal32_stream.cpp, test/test_decimal64_stream.cpp, test/test_strtod.cpp
=> Add std::setprecision support

include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/comparison.hpp, test/Jamfile, test/random_decimal64_math.cpp, test/random_mixed_decimal_math.cpp, test/test_constants.cpp, test/test_float_conversion.cpp, test/test_git_issue_271.cpp
=> Fix truncation in comparison functions for decimal64

include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/io.hpp, test/test_decimal32.cpp
=> New basis for decimal32

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp
=> Replace internals of decimal64

include/boost/decimal/detail/bit_cast.hpp, include/boost/decimal/detail/emulated128.hpp, include/boost/decimal/detail/ryu/ryu_generic_128.hpp
=> Make uint128 trivial

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/random_decimal32_math.cpp, test/random_decimal64_math.cpp
=> Add bitwise logical operators

include/boost/decimal.hpp, include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/attributes.hpp, include/boost/decimal/detail/emulated256.hpp, include/boost/decimal/detail/integer_search_trees.hpp, include/boost/decimal/detail/type_traits.hpp, include/boost/decimal/fwd.hpp, test/Jamfile, test/test_decimal128_basis.cpp
=> Decimal128 Basis

include/boost/decimal/decimal128.hpp, include/boost/decimal/detail/config.hpp, include/boost/decimal/detail/emulated128.hpp, include/boost/decimal/detail/from_chars_integer_impl.hpp, include/boost/decimal/detail/normalize.hpp, include/boost/decimal/detail/parser.hpp, include/boost/decimal/detail/power_tables.hpp, include/boost/decimal/detail/to_integral.hpp, test/Jamfile, test/random_decimal128_math.cpp, test/test_emulated128.cpp
=> Decimal128 Addition

include/boost/decimal/detail/ryu/ryu_generic_128.hpp
=> Fix ODR violation on PPC64LE

include/boost/decimal/decimal128.hpp, include/boost/decimal/detail/emulated128.hpp, include/boost/decimal/detail/emulated256.hpp, include/boost/decimal/detail/integer_search_trees.hpp, include/boost/decimal/detail/ryu/ryu_generic_128.hpp, test/random_decimal128_math.cpp
=> Implement multiplication for decimal128, decimal128

include/boost/decimal/decimal128.hpp, test/random_decimal128_math.cpp
=> Mixed type addition for decimal128

CMakeLists.txt, include/boost/decimal/detail/config.hpp, include/boost/decimal/detail/countl.hpp, include/boost/decimal/detail/emulated128.hpp, include/boost/decimal/detail/fast_float/compute_float64.hpp
Improves support for bare metal platforms
=> Improve standalone support

include/boost/decimal/decimal128.hpp, test/random_decimal128_math.cpp
=> Mixed sub for decimal128

include/boost/decimal/decimal128.hpp, test/random_decimal128_math.cpp
Closes: #312 
Closes: #319 
Closes: #320
=> Mixed mul and div for decimal128

include/boost/decimal/decimal128.hpp
=> Decimal128 compound operators

include/boost/decimal/detail/emulated128.hpp, include/boost/decimal/hash.hpp, test/Jamfile, test/test_hash.cpp
=> Add support for std::hash to decimal128

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/nan.hpp, test/test_cmath.cpp
=> Add cmath nan function

include/boost/decimal/detail/cmath/fmax.hpp, include/boost/decimal/detail/cmath/fmin.hpp, include/boost/decimal/detail/cmath/hypot.hpp, test/concepts_test.cpp, test/test_cmath.cpp
=> Allow mixed arguments in cmath functions 

include/boost/decimal/detail/io.hpp, include/boost/decimal/detail/to_string.hpp, test/Jamfile, test/test_to_string.cpp
=> Add to_string

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/asin.hpp, test/Jamfile, test/test_asin.cpp
=> Add Arcsin

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/acos.hpp, include/boost/decimal/detail/cmath/asin.hpp, include/boost/decimal/detail/cmath/impl/asin_impl.hpp, test/Jamfile, test/test_acos.cpp
=> Add arccos 

.github/workflows/ci.yml, include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/fma.hpp, include/boost/decimal/detail/cmath/impl/asin_impl.hpp, test/test_asin.cpp
=> Asin support for decimal128

include/boost/decimal/detail/parser.hpp, test/test_float_conversion.cpp
=> Transpose changes from charconv parser

include/boost/decimal/decimal128.hpp, include/boost/decimal/detail/cmath/remquo.hpp, include/boost/decimal/detail/to_integral.hpp, test/test_cmath.cpp
=> Fix remquo for decimal128

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/laguerre.hpp, test/Jamfile, test/test_laguerre.cpp
=> Implement and test Laguerre

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/assoc_laguerre.hpp, test/Jamfile, test/test_assoc_laguerre.cpp
=> Implement and test assoc_laguerre

include/boost/decimal.hpp, include/boost/decimal/charconv.hpp, include/boost/decimal/detail/chars_format.hpp, include/boost/decimal/detail/config.hpp, include/boost/decimal/detail/from_chars_result.hpp, test/CMakeLists.txt, test/Jamfile, test/test_from_chars.cpp
Closes: #406 
Closes: #407 
Closes: #408
=> Begin adding `from_chars` support

include/boost/decimal/charconv.hpp, include/boost/decimal/detail/buffer_sizing.hpp, include/boost/decimal/detail/memcpy.hpp, include/boost/decimal/detail/to_chars_integer_impl.hpp, include/boost/decimal/detail/to_chars_result.hpp, test/Jamfile, test/test_to_chars.cpp
Closes: #411 
Closes: #412 
Closes: #413
=> Add preliminary `to_chars` support

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/test_from_chars.cpp
=> Add operator= for integral types

doc/decimal/examples.adoc, doc/decimal/generic_decimal.adoc
=> Add examples to docs

include/boost/decimal/charconv.hpp, test/test_from_chars.cpp
=> Add hex support to `from_chars`

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/Jamfile, test/github_issue_426.cpp
=> Add conversion from floating point values

include/boost/decimal/charconv.hpp, test/test_to_chars.cpp
=> Fix `to_chars` handling of zero

include/boost/decimal/charconv.hpp, include/boost/decimal/detail/emulated128.hpp, test/test_to_chars.cpp
=> `to_chars` for hex formatting

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/legendre.hpp, test/Jamfile, test/test_legendre.cpp
=> Implement Legendre

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal64.hpp
=> Add operator%= to decimal64 and 128

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/hash.hpp, test/Jamfile, test/github_issue_448.cpp
=> Add and test trivial copy and move constructors

include/boost/decimal/charconv.hpp, test/test_to_chars.cpp
=> Remove old code path from to_chars_fixed_impl that causes precision errors

include/boost/decimal.hpp, include/boost/decimal/charconv.hpp, include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/io.hpp, test/Jamfile, test/roundtrip_decimal64.cpp, test/test_decimal32_stream.cpp, test/test_decimal64_stream.cpp, test/test_strtod.cpp, test/test_to_chars.cpp
Closes: #19 
Closes: #457 
Closes: #458
=> Use charconv to implement formatted IO

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/apply_sign.hpp, include/boost/decimal/detail/emulated128.hpp, include/boost/decimal/detail/fenv_rounding.hpp, include/boost/decimal/detail/from_chars_integer_impl.hpp, test/Jamfile, test/test_implicit_integral_conversion.cpp
=> Enable and test implicit conversion from integral types

include/boost/decimal/cstdlib.hpp, test/test_strtod.cpp
=> Fix bugs in strtod testing

include/boost/decimal/charconv.hpp, test/test_to_chars.cpp
=> Fix printing of values in fixed format that are negative

include/boost/decimal/detail/cmath/remquo.hpp, test/Jamfile, test/test_cmath.cpp, test/test_remainder_remquo.cpp
Removes unneeded additional conversion that caused incorrect results for decimal128
=> Fix remquo handling of negative values and decimal128

test/test_cmath.cpp
=> More cmath coverage

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/concepts.hpp, include/boost/decimal/detail/to_chars_integer_impl.hpp, include/boost/decimal/detail/to_float.hpp, include/boost/decimal/detail/to_integral.hpp, include/boost/decimal/detail/to_string.hpp
=> More use of concepts instead of SFINAE when available 

include/boost/decimal/charconv.hpp, include/boost/decimal/detail/to_string.hpp, test/test_to_string.cpp
=> Use charconv in to_string implementation

doc/decimal/generic_decimal.adoc, include/boost/decimal/cstdlib.hpp, include/boost/decimal/detail/io.hpp, include/boost/decimal/detail/locale_conversion.hpp, test/test_decimal32_stream.cpp
=> Add and document locale dependence of stream operators

doc/decimal/cfenv.adoc, doc/decimal/cfloat.adoc, doc/decimal/charconv.adoc, doc/decimal/cmath.adoc, doc/decimal/cstdlib.adoc, doc/decimal/generic_decimal.adoc, doc/decimal/numbers.adoc, doc/decimal/overview.adoc, doc/decimal/type_traits.adoc
Closes: #486 
Closes: #487 
Closes: #489
=> Documentation Updates

.drone.jsonnet, .github/workflows/ci.yml
=> Update CI toolchains

README.md, conan/conanfile.py, conan/targets.cmake, ports/decimal/b2-options.cmake, ports/decimal/portfile.cmake, ports/decimal/vcpkg.json
=> Add vcpkg and Conan packages

.github/workflows/ci.yml
Upstream issue has been resolved
=> Activate 32-bit MSYS run

test/benchmark_libdfp.c, test/benchmarks.cpp
Closes: #563
This is written using C11 so is not included in the CI. Can be run locally from the command line using:
`gcc-14 -o benchmark_libdfp benchmark_libdfp.c -std=c11 -O3 -lm -march=native`
followed by
`./benchmark_libdfp`
=> Add GCC/libdfp benchmarks

include/boost/decimal.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/detail/attributes.hpp, include/boost/decimal/detail/comparison.hpp, include/boost/decimal/detail/power_tables.hpp, include/boost/decimal/detail/to_integral.hpp, include/boost/decimal/detail/type_traits.hpp, include/boost/decimal/fwd.hpp, test/Jamfile, test/benchmarks.cpp, test/random_decimal32_fast_comp.cpp, test/test_decimal32_fast_basis.cpp
=> Decimal32_fast basis

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/config.hpp
=> Reduce decoding branches

include/boost/decimal.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/add_impl.hpp, include/boost/decimal/detail/cmath/fma.hpp, include/boost/decimal/detail/div_impl.hpp, include/boost/decimal/detail/mul_impl.hpp, include/boost/decimal/detail/sub_impl.hpp, include/boost/decimal/detail/type_traits.hpp, include/boost/decimal/fwd.hpp, test/Jamfile, test/random_decimal64_fast_comp.cpp, test/random_decimal64_fast_math.cpp
=> `decimal64_fast` basis

include/boost/decimal/decimal64_fast.hpp, test/random_decimal64_fast_comp.cpp, test/random_decimal64_fast_math.cpp
=> Add support for mixed decimal64_fast and Integer operations

include/boost/decimal/cmath.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/cmath/fma.hpp, include/boost/decimal/detail/cmath/impl/asin_impl.hpp, include/boost/decimal/detail/cmath/impl/assoc_legendre_lookup.hpp, include/boost/decimal/detail/cmath/impl/atan_impl.hpp, include/boost/decimal/detail/cmath/impl/cos_impl.hpp, include/boost/decimal/detail/cmath/impl/cosh_impl.hpp, include/boost/decimal/detail/cmath/impl/expm1_impl.hpp, include/boost/decimal/detail/cmath/impl/lgamma_impl.hpp, include/boost/decimal/detail/cmath/impl/log1p_impl.hpp, include/boost/decimal/detail/cmath/impl/log_impl.hpp, include/boost/decimal/detail/cmath/impl/riemann_zeta_impl.hpp, include/boost/decimal/detail/cmath/impl/sin_impl.hpp, include/boost/decimal/detail/cmath/impl/sinh_impl.hpp, include/boost/decimal/detail/cmath/impl/tanh_impl.hpp, include/boost/decimal/detail/cmath/impl/tgamma_impl.hpp, include/boost/decimal/detail/promotion.hpp, test/test_cmath.cpp
=> `decimal64_fast` cmath additions

include/boost/decimal.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/type_traits.hpp, include/boost/decimal/fwd.hpp, test/Jamfile, test/random_decimal128_fast_comp.cpp
=> Begin implementing decimal128_fast

include/boost/decimal/decimal128_fast.hpp, test/random_decimal128_fast_comp.cpp, test/random_decimal128_fast_math.cpp
=> Implement mixed arithmetic and comparisions for decimal128_fast

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/beta.hpp, test/Jamfile, test/test_beta.cpp
=> Implement beta

include/boost/decimal/cstdlib.hpp, include/boost/decimal/detail/cmath/acos.hpp, include/boost/decimal/detail/cmath/asin.hpp, include/boost/decimal/detail/cmath/assoc_legendre.hpp, include/boost/decimal/detail/cmath/legendre.hpp
=> Replace NaN types for invalid arguments

include/boost/decimal/charconv.hpp, include/boost/decimal/detail/parser.hpp, include/boost/decimal/detail/to_float.hpp, test/Jamfile, test/random_decimal128_fast_math.cpp, test/roundtrip_decimal128_fast.cpp, test/test_beta.cpp, test/test_from_chars.cpp, test/test_parser.cpp, test/test_sin_cos.cpp, test/test_tgamma.cpp
Fixes some bugs along the way as expected
Closes: #668
=> Improve fast type coverage

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/sub_impl.hpp
Closes: #686 
Closes: #694 
Closes: #695
=> Improve 64 and 128 bit subtraction

include/boost/decimal/decimal64_fast.hpp, test/cuda_jamfile, test/test_decimal64_fast_add.cu, test/test_decimal64_fast_div.cu, test/test_decimal64_fast_mul.cu, test/test_decimal64_fast_sub.cu
Adds support for add, sub, mul, and div for decima64_fast
=> Decimal64 fast cuda basics

.github/workflows/ci.yml, README.md, doc/decimal/overview.adoc
Also updates list of tested platforms in the docs
=> Add intel compiler to CI

conan/conanfile.py, doc/decimal/benchmarks.adoc, ports/decimal/portfile.cmake, test/benchmark_libdfp.c, test/benchmarks.cpp
=> Merge for v2.3.1

include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/dpd_conversion.hpp, test/test_dpd_conversions.cpp
=> Implement 64 bit DPD conversions

.github/workflows/ci.yml
macOS-12 is pending removal and 15 was just added
=> Replace macos-12 with 15

fuzzing/Jamfile, fuzzing/make-corpus.py
Currently all of the seed corpus is in one file. It should be one line per file so this python script cuts it up like it should be
=> Improved Fuzzing

doc/decimal/charconv.adoc
=> Add note on normalization in charconv to docs

doc/decimal/cmath.adoc
=> Remove domain error verbiage for quantexp

doc/decimal/decimal128.adoc, doc/decimal/decimal128_fast.adoc, doc/decimal/decimal32.adoc, doc/decimal/decimal32_fast.adoc, doc/decimal/decimal64.adoc, doc/decimal/decimal64_fast.adoc, include/boost/decimal/detail/to_integral.hpp, test/roundtrip_decimal128.cpp, test/roundtrip_decimal128_fast.cpp, test/roundtrip_decimal32.cpp, test/roundtrip_decimal32_fast.cpp, test/roundtrip_decimal64.cpp
=> Improve and document explicit conversion saturation

include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/detail/div_impl.hpp, include/boost/decimal/detail/mul_impl.hpp, include/boost/decimal/detail/power_tables.hpp
=> Make powers of 10 calculations constexpr

test/test_ellint_1.cpp, test/test_ellint_2.cpp
=> Increase ellint tolerances

test/test_to_chars.cpp
=> Test fixed zero with precision argument

include/boost/decimal/charconv.hpp, include/boost/decimal/cstdlib.hpp, include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/attributes.hpp, include/boost/decimal/detail/comparison.hpp, include/boost/decimal/detail/fenv_rounding.hpp, include/boost/decimal/detail/mul_impl.hpp, include/boost/decimal/detail/promotion.hpp, include/boost/decimal/detail/type_traits.hpp, include/boost/decimal/numbers.hpp
=> Use traits to reduce duplication / improve logic 

build.jam
=> Fix library alias

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/cmath/next.hpp, test/github_issue_798.cpp
=> Fix next after part 2

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, test/roundtrip_decimal128.cpp, test/roundtrip_decimal128_fast.cpp, test/roundtrip_decimal32.cpp, test/roundtrip_decimal32_fast.cpp, test/roundtrip_decimal64.cpp
=> Remove conversions to 8 and 16 bit integer types

include/boost/decimal/detail/to_integral.hpp, test/benchmarks.cpp
=> Fix boundary check in to_integer

include/boost/decimal/charconv.hpp, include/boost/decimal/detail/memcpy.hpp, include/boost/decimal/detail/to_chars_integer_impl.hpp, test/benchmarks.cpp
=> Fix `to_chars` for `decimal128` being disproportionally slower

doc/modules/ROOT/pages/benchmarks.adoc, test/benchmarks.cpp
=> Update x64 Windows Benchmarks in Docs

include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/components.hpp
=> Replace internal fast types with fixed types

include/boost/decimal/charconv.hpp, include/boost/decimal/detail/buffer_sizing.hpp, test/Jamfile
=> Fix variable shadowing

doc/modules/ROOT/nav.adoc, doc/modules/ROOT/pages/cfenv.adoc, doc/modules/ROOT/pages/cfloat.adoc, doc/modules/ROOT/pages/charconv.adoc, doc/modules/ROOT/pages/cmath.adoc, doc/modules/ROOT/pages/conversions.adoc, doc/modules/ROOT/pages/cstdio.adoc, doc/modules/ROOT/pages/cstdlib.adoc, doc/modules/ROOT/pages/file_structure.adoc, doc/modules/ROOT/pages/format.adoc, doc/modules/ROOT/pages/functional.adoc, doc/modules/ROOT/pages/limits.adoc, doc/modules/ROOT/pages/literals.adoc
=> Improve documentation on relevant headers

doc/modules/ROOT/pages/fast_types.adoc
=> Expand the fast type explanation section

include/boost/decimal/charconv.hpp, test/test_to_chars.cpp
=> New `<charconv>` path bug fixes

include/boost/decimal/detail/fenv_rounding.hpp, include/boost/decimal/detail/u256.hpp
Implements specific div mods that utilize our software implementation of big ints to give us div and mod from a single operation
=> Improve performance of new rounding facilities

test/test_pow.cpp
=> Increase tolerances for decimal32_t pow
