include/boost/decimal.hpp, include/boost/decimal/common_math.hpp, include/boost/decimal/decimal32.hpp, test/random_decimal32_math.cpp
ISO allows for arithmetic between any integral type, and any decimal type
=> Enable mixed type arithmetic

include/boost/decimal.hpp, include/boost/decimal/common_comp.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/config.hpp, test/Jamfile, test/random_decimal32_comp.cpp
Like arithmetic operators decimal32 is allowed to be compared to all integer types
=> Enable mixed type comparison

include/boost/decimal/cmath.hpp, include/boost/decimal/common_math.hpp, include/boost/decimal/decimal32.hpp, test/CMakeLists.txt, test/test_decimal32.cpp, test/test_decimal32_cmath.cpp
Also fixes floor, ceil, and comparison operators performance around 0.
=> Implement fmod

include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/cmath/frexp.hpp, include/boost/decimal/detail/cmath/ilogb.hpp, test/test_decimal32_cmath.cpp
Add the non-finite paths and changes the return to be the unbiased exponent:
`
Extracts the value of the unbiased exponent from the floating-point argument num, and returns it as a signed integer value. The library provides overloads of std::ilogb for all cv-unqualified floating-point types as the type of the parameter num. (since C++23)
`
Closes: #86 
@ckormanyos
=> Change handling of ilogb

include/boost/decimal/common_math.hpp, include/boost/decimal/decimal32.hpp, test/random_decimal32_math.cpp, test/test_decimal32.cpp
Allows for generic division between decimal types and integer types
Closes: #113 
Closes: #114
=> Make div generic

include/boost/decimal/decimal32.hpp
The purpose of this PR is to figure out better ways to detect modern `__cplusplus` version(s).
Hi Matt (@mborland), my VC142 tests positive for the first PP-query in
```
#if __cplusplus <= 202002L || _MSVC_LANG <= 202002L
```
This is because MSVC empirically seems to have poor support for `__cplusplus`.
=> Awarenes for __cplusplus and _MSC_VER

include/boost/decimal/detail/cmath/exp.hpp, test/test_acosh.cpp, test/test_cosh.cpp, test/test_edges_and_behave.cpp, test/test_exp.cpp, test/test_expm1.cpp, test/test_frexp_ldexp.cpp, test/test_log.cpp, test/test_log1p.cpp, test/test_sinh.cpp, test/test_sqrt.cpp, test/test_tanh.cpp
The purpose of this PR is to extend the testing of the `exp()` function (known from `<cmath>`) to 64-bit decimal.
Also in this PR it was decided to see how the Pade approximation plays out for `exp()`, as this seems to give better precision for lower run-time cost.
=> Update and test exp 64-bit and Pade approx

include/boost/decimal/decimal128.hpp, test/random_decimal128_math.cpp
=> Add bitwise operators to decimal128

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/emulated128.hpp, test/roundtrip_decimal128.cpp, test/roundtrip_decimal32.cpp, test/roundtrip_decimal64.cpp
=> Add conversions for builtin 128-bit types

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/atan.hpp, include/boost/decimal/detail/cmath/atan2.hpp, test/Jamfile, test/test_atan.cpp, test/test_atan2.cpp
=> Implement atan2

include/boost/decimal/detail/wide-integer/uintwide_t.hpp
Avoids any possible collisions if someone is also using the OG wide integer
=> Rename all WIDE_INTEGER* macros

CMakeLists.txt, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/config.hpp, include/boost/decimal/detail/emulated128.hpp, include/boost/decimal/detail/emulated256.hpp, include/boost/decimal/detail/from_chars_integer_impl.hpp, include/boost/decimal/detail/integer_search_trees.hpp, include/boost/decimal/detail/parser.hpp, test/test_decimal32.cpp
Was only used for attribute we had a backup for and the type of builtin 128 integers
=> Remove boost.config dependency

include/boost/decimal/detail/parser.hpp, test/test_float_conversion.cpp
Closes: #158 
Groundwork for enabling hex floats in `from_chars`
=> Add hex support to the parser

include/boost/decimal/charconv.hpp, test/test_to_chars.cpp
One-half of the solution to #434
=> Fix for `to_chars` with specified precision and `chars_format::fixed`

include/boost/decimal/charconv.hpp, test/test_to_chars.cpp
=> Fix `to_chars` with specified precision and `chars_format::scientific`

include/boost/decimal/detail/cmath/cbrt.hpp, test/Jamfile, test/test_cbrt.cpp, test/test_cmath.cpp
Fixes: #440 
@ckormanyos I simplified the step and initial guess which has this working correctly. I still think it's worth investigating a much better initial guess if that's something you still want to pursue. 
I am going to keep separating tests out of the giant test_cmath file because I found this was tested incorrectly (wasn't taking the abs of the float distance) and it's easier to run GDB through smaller files.
=> Fix cbrt and expand testing

include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/ellint_1.hpp, include/boost/decimal/detail/cmath/impl/ellint_rc.hpp, include/boost/decimal/detail/cmath/impl/ellint_rf.hpp, test/Jamfile, test/test_ellint_1.cpp
=> Add comp_ellint_1

include/boost/decimal/detail/cmath/cbrt.hpp, include/boost/decimal/detail/cmath/sqrt.hpp, test/test_cmath.cpp
Closes: #442 
Closes: #251 
For cbrt reduced average iterations from 11.6 to 9.4 with decimal32 with numbers in the testing range (1, 1e3). (0,1) is not changed.
=> Improve root guesses

.drone/drone.bat, .drone/drone.sh
Since the jsonnet method doesn't call functions.star, please add this DRONE_STAGE_MACHINE variable to any projects, as shown.
The recent test is inconclusive, because the agent machine was not known.  An ephemeral server in the cloud is showing "1/2 status checks passed" as if there are hardware problems.
How about splitting the gcc 7 job into two separate parts: 32, and 64 bit.
=> Add drone debugging variable DRONE_STAGE_MACHINE

doc/decimal/cstdio.adoc, include/boost/decimal/cstdio.hpp, include/boost/decimal/detail/locale_conversion.hpp, test/Jamfile, test/test_big_uints.cpp, test/test_fprintf.cpp, test/test_snprintf.cpp
=> Add fprintf and printf

doc/decimal/config.adoc, include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/Jamfile, test/github_issue_426.cpp, test/test_assoc_legendre.cpp, test/test_boost_math_univariate_stats.cpp, test/test_explicit_floats.cpp, test/test_legendre.cpp
Adds configuration macro `BOOST_DECIMAL_ALLOW_IMPLICIT_CONVERSIONS` if the user wants it.
=> Make float conversions explicit again

doc/decimal/benchmarks.adoc, test/benchmarks.cpp
Fixes resolution, adds sqrt and `<charconv>`.
Closes: #508
=> Add additional benchmarks

.github/workflows/ci.yml
This warning has been fixed upstream in Charconv but breaks the build in GCC-13
=> Fix gcc-13 build

doc/decimal/benchmarks.adoc, include/boost/decimal/charconv.hpp, include/boost/decimal/detail/normalize.hpp, include/boost/decimal/detail/remove_trailing_zeros.hpp, include/boost/decimal/detail/type_traits.hpp, test/test_snprintf.cpp
Closes: #515 
Closes: #516 
For add and sub Decimal64 is ~2x faster, and Decimal128 is ~10x faster.
=> Improve operations expanding or shrinking significand

include/boost/decimal/decimal128.hpp, include/boost/decimal/detail/cmath/impl/taylor_series_result.hpp, include/boost/decimal/detail/cmath/tgamma.hpp, include/boost/decimal/detail/remove_trailing_zeros.hpp, test/Jamfile, test/github_issue_519.cpp, test/test_tgamma.cpp
Closes: #520 
Speeds up multiplication and work around for add step. During the call to normalize in preparation for the add step rounding was occurring which is equivalent just calling operator+.
=> Fix decimal128 fma

include/boost/decimal/detail/remove_trailing_zeros.hpp, test/Jamfile, test/test_remove_trailing_zeros.cpp, tools/granlund-montgomery.py
@jk-jeon I thought you might be interested in these results. I took the branchless Granlund-Montgomery from your [repo](https://github.com/jk-jeon/rtz_benchmark/blob/master/source/main.cpp) for `std::uint32_t` and `std::uint64_t` and then adapted a 128-bit case. I also added a test set for every representable power of 10 to see if the result is always 1. I found that in the 32 bit and 64 bit cases an extra step was needed beyond what you had in your repo as it was stopping at 7 and 15 zeros removed respectively. In the 128-bit case I ended up going for two passes since with t = 32, there is no modular inverse so the whole calculation becomes garbage.
=> Faster zero removal

include/boost/decimal/decimal128.hpp, include/boost/decimal/detail/integer_search_trees.hpp, test/test_to_chars.cpp
=> Improve some basic 128-bit operations

doc/decimal/charconv.adoc, include/boost/decimal/charconv.hpp, include/boost/decimal/detail/attributes.hpp, test/test_to_chars.cpp
=> Add buffer sizing for charconv

.github/workflows/ci.yml
Github broke 22.04: https://github.com/actions/runner-images/issues/9866
=> Update GCC13 runner os

include/boost/decimal/detail/promotion.hpp, test/test_promotion.cpp
=> Fix promotion system with inclusion of `decimal32_fast`

doc/decimal/cmath.adoc, include/boost/decimal/cmath.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/cmath/trunc.hpp, include/boost/decimal/detail/cmath/trunc_to.hpp, include/boost/decimal/detail/integer_search_trees.hpp, include/boost/decimal/detail/power_tables.hpp, include/boost/decimal/detail/shrink_significand.hpp, test/Jamfile, test/test_fixed_width_trunc.cpp
Closes: #565 
@ckormanyos This one was by request from the discussion on the ML. I am open to a better name than overloading `trunc` even though that's what it does; truncates to a fixed number of decimal places (with appropriate rounding).
=> Fixed width rounding

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/comparison.hpp, include/boost/decimal/detail/integer_search_trees.hpp
=> Improve comparison functions

include/boost/decimal/detail/to_integral.hpp, test/benchmarks.cpp
=> Add Decimal64 fast to benchmarks

include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/detail/add_impl.hpp, include/boost/decimal/detail/config.hpp, include/boost/decimal/detail/div_impl.hpp, include/boost/decimal/detail/mul_impl.hpp, include/boost/decimal/detail/normalize.hpp, include/boost/decimal/detail/power_tables.hpp, include/boost/decimal/detail/sub_impl.hpp, test/test_decimal32_fast_basis.cpp, test/test_decimal_quantum.cpp
- Normalizes the value in the constructor rather than at each operation
- Inlines and optimized add, sub, mul, div
@ckormanyos Prior to this PR the benchmarks were showing that `decimal32_fast` was running in 0.686 of the time that `decimal32` was. Now it's down to 0.251.
Closes: #619
=> Make dec32_fast even faster

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, test/Jamfile, test/test_fast_math.cpp
Closes: #623 
Take an apporach similar to intel where `isnan`, `isinf` return false but go one step further and just completely remove the branches to maximize speedup. We also have no control over what `-ffast-math` does. Benchmarks are up to 20% faster without these checks enabled.
=> Offer fast math macro

.github/workflows/ci.yml, include/boost/decimal/charconv.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/detail/attributes.hpp, include/boost/decimal/detail/cmath/fma.hpp, include/boost/decimal/detail/cmath/impl/asin_impl.hpp, include/boost/decimal/detail/cmath/impl/assoc_legendre_lookup.hpp, include/boost/decimal/detail/cmath/impl/atan_impl.hpp, include/boost/decimal/detail/cmath/impl/cos_impl.hpp, include/boost/decimal/detail/cmath/impl/cosh_impl.hpp, include/boost/decimal/detail/cmath/impl/expm1_impl.hpp, include/boost/decimal/detail/cmath/impl/lgamma_impl.hpp, include/boost/decimal/detail/cmath/impl/log1p_impl.hpp, include/boost/decimal/detail/cmath/impl/log_impl.hpp, include/boost/decimal/detail/cmath/impl/riemann_zeta_impl.hpp, include/boost/decimal/detail/cmath/impl/sin_impl.hpp, include/boost/decimal/detail/cmath/impl/sinh_impl.hpp, include/boost/decimal/detail/cmath/impl/tanh_impl.hpp, include/boost/decimal/detail/cmath/impl/tgamma_impl.hpp, include/boost/decimal/detail/cmath/remquo.hpp, include/boost/decimal/detail/div_impl.hpp, include/boost/decimal/detail/fenv_rounding.hpp, include/boost/decimal/detail/mul_impl.hpp, include/boost/decimal/detail/promotion.hpp, include/boost/decimal/numbers.hpp, test/test_asin.cpp, test/test_cmath.cpp, test/test_promotion.cpp
=> Add cmath support to decimal128_fast

include/boost/decimal/detail/integer_search_trees.hpp, include/boost/decimal/detail/power_tables.hpp, test/roundtrip_decimal32.cpp, test/roundtrip_decimal32_fast.cpp, test/roundtrip_decimal64.cpp, test/test_decimal32.cpp, test/test_decimal32_fast_basis.cpp
Closes: #643 
Provides geometric mean of ~27% uplift on basis operations for `decimal128`
=> Different improvement of counting methods

include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/add_impl.hpp, test/test_decimal64_fast_basis.cpp
Normalize the values in the constructor and remove all the calls to normalize in the basis functions
Closes #639
=> Improvements to decimal64_fast

doc/decimal/benchmarks.adoc, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/detail/add_impl.hpp
Closes: #656 
Provides 2.375x speedup vs develop and 3.236x speedup vs `decimal128`
=> Faster dec128 fast

include/boost/decimal/detail/integer_search_trees.hpp, test/test_big_uints.cpp
Improves `decimal128` by 6.369x and `decimal128_fast` by 4.651 in >=C++17 modes.
=> Improve `num_digits()` for `uint256_t`

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/add_impl.hpp, include/boost/decimal/detail/cmath/fma.hpp, include/boost/decimal/detail/cmath/frexp10.hpp, include/boost/decimal/detail/cmath/impl/riemann_zeta_impl.hpp, include/boost/decimal/detail/comparison.hpp, include/boost/decimal/detail/div_impl.hpp, include/boost/decimal/detail/mul_impl.hpp, include/boost/decimal/detail/promote_significand.hpp, include/boost/decimal/detail/shrink_significand.hpp, include/boost/decimal/detail/sub_impl.hpp, include/boost/decimal/detail/to_integral.hpp, test/random_decimal128_math.cpp, test/random_decimal32_fast_math.cpp, test/random_decimal32_math.cpp, test/random_decimal64_fast_math.cpp, test/random_decimal64_math.cpp, test/test_cmath.cpp, test/test_decimal32.cpp, test/test_decimal32_fast_basis.cpp, test/test_decimal64_fast_basis.cpp, test/test_sin_cos.cpp, test/test_zeta.cpp
Closes: #672 
Closes: #673 
Closes: #674
Closes: #675
=> Improved basic operators for 32 and 64 bit types

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/config.hpp, include/boost/decimal/detail/div_impl.hpp, include/boost/decimal/detail/emulated128.hpp, include/boost/decimal/detail/mul_impl.hpp, include/boost/decimal/detail/sub_impl.hpp
Closes: #678 
Closes: #679 
Closes: #680 
Closes: #681 
Closes: #618
=> Refactor decimal128 and decimal128_fast

test/compare_dec128_and_fast.cpp, test/random_decimal128_fast_math.cpp, test/test_cmath.cpp
=> Improve testing coverage

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/detail/add_impl.hpp, include/boost/decimal/detail/config.hpp, test/test_decimal32.cpp
Removes a few branches and swaps from the existing implementation
Closes: #687
=> Improve 32-bit addition implementation 

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/detail/sub_impl.hpp
=> Remove recursive call from 32 bit operator-

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/cmath/fpclassify.hpp
=> Simplify non-finite number functions and handling

.drone.jsonnet, .github/workflows/ci.yml, .github/workflows/fuzz.yml, .github/workflows/qemu.yml, include/boost/decimal/detail/bit_layouts.hpp, include/boost/decimal/detail/ryu/ryu_generic_128.hpp, test/test_beta.cpp, test/test_decimal32_fast_stream.cpp, test/test_decimal32_stream.cpp, test/test_snprintf.cpp, test/test_strtod.cpp
=> Add ppc64le runs to CI

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/detail/comparison.hpp
Closes: #702 
New runtimes in the comp benchmarks are 0.776 for decimal32 and 0.809 for decimal32_fast.
=> Improve comparison operators for decimal32 and decimal32_fast

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/detail/comparison.hpp
Closes: #701 
Closes: #707 
Closes: #708 
New benchmarks for decimal128 show >20% speedup and decimal128_fast nets ~30%
=> Improve 128 bit comparisons

include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/detail/comparison.hpp
Avoid duplicate non-finite checks in decimal32_fast comparisons
=> Decimal32 fast comps v2

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/cuda_jamfile, test/test_decimal32_add.cu, test/test_decimal32_div.cu, test/test_decimal32_mul.cu, test/test_decimal32_sub.cu, test/test_decimal64_add.cu, test/test_decimal64_div.cu, test/test_decimal64_mul.cu, test/test_decimal64_sub.cu
Adds CUDA support for decimal32 and decimal64 operators add, sub, mul, and div
=> Add CUDA support to decimal32 and decimal64 basic ops

include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/comparison.hpp
Breaks the decoding of the type into multiple steps rather than doing it all up front, because it many cases that is unnecessary. Results in about a 6.5% speedup in all operations across `decimal32`.
=> Improve comparisons for decimal32

include/boost/decimal/detail/attributes.hpp, include/boost/decimal/detail/config.hpp, include/boost/decimal/numbers.hpp
Clang 19 changed the handling of template variables and specializations of template variables that completely broke what we had. Now make detail functions that calculate the correct value and only have a single template variable that is equal to the result of that function.
=> Fix clang19

include/boost/decimal/decimal64.hpp, include/boost/decimal/detail/comparison.hpp
Provides a >30% speedup to `decimal64`s comparisons timing
=> Improved comparisons for `decimal64`

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/detail/mul_impl.hpp
Checking the number of digits is a O(log(n)) operation. If we can fit the result of significand multiplication into the range of a `u128` then we avoid the 256-bit multiplication all together.
=> Faster dec128 mul

build.jam, doc/Jamfile, test/Jamfile
Updates our toolchain to support b2's modular format. Also adds support for boost look which is an improvement over the regular asciidoctor layout
=> Add support for b2 modular builds and boostlook

doc/decimal/conversions.adoc, include/boost/decimal/bid_conversion.hpp, include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal64.hpp, test/test_bid_conversions.cpp
=> Reduce language requirement for constexpr BID conversions

doc/decimal/conversions.adoc, include/boost/decimal/bid_conversion.hpp, include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/dpd_conversion.hpp, test/test_dpd_conversions.cpp
=> Add 128-bit DPD conversions

doc/decimal/charconv.adoc, doc/decimal/config.adoc, include/boost/decimal/charconv.hpp, include/boost/decimal/detail/config.hpp, test/test_from_chars.cpp, test/test_to_chars.cpp
=> Enable interoperability with `std::` types from `<charconv>`

doc/decimal/literals.adoc, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/literals.hpp, test/test_literals.cpp
Closes: #751 
Also fixes the range of dec32_fast being slightly larger than it should be, and a typo in the dec32 literals docs
=> Add literals for fast types

.gitignore, include/boost/decimal/bid_conversion.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/power_tables.hpp, include/boost/decimal/dpd_conversion.hpp, meta/libraries.json, modules/Jamfile, modules/decimal.cxx
Closes: #746 
Gets things working again with GCC-14 in addition to adding our new types
=> Add module support to the fast types

include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/fast_float/compute_float80_128.hpp, include/boost/decimal/detail/to_float.hpp
I think it's best to not offer `__float128` support until demanded based off all the issue that charconv has had because of that decision.
=> Enable 80 and 128 bit long double conversions

doc/decimal/charconv.adoc, doc/decimal/config.adoc, include/boost/decimal/charconv.hpp, include/boost/decimal/detail/config.hpp, modules/decimal.cxx, test/test_from_chars.cpp
Matches what the consumers asked for in boost.charconv
Closes: #764
=> Add string and string_view interfaces to `from_chars`

include/boost/decimal/literals.hpp
Warning was emitted by Clang-20
=> Fix deprecated whitespace in literal definition

doc/decimal/examples.adoc, examples/moving_average.cpp, examples/statistics.cpp, examples/where_file.hpp, test/Jamfile
=> Add example using Boost.Math

include/boost/decimal/charconv.hpp, test/test_to_chars.cpp
=> Fix for 777

.drone.jsonnet, include/boost/decimal/detail/cmath/fma.hpp, include/boost/decimal/detail/cmath/impl/remez_series_result.hpp, include/boost/decimal/detail/cmath/impl/taylor_series_result.hpp
Also updates the special function evaluation to use our unchecked FMA to speed things up as suggested by @ckormanyos
=> Implement proper 64 bit FMA

examples/format.cpp, include/boost/decimal/format.hpp, test/test_format.cpp
Used the wrong library name to the right effect.
=> Fix macro naming for format

examples/format.cpp, include/boost/decimal/format.hpp, test/test_format.cpp
Fixes and tests formatting of capitalized non-finite values
=> Capital format

doc/decimal.adoc, doc/decimal/basics.adoc, doc/decimal/overview.adoc
Closes: #784 
@akrzemi1 let me know if there's anything you think is missing from the expanded basics section. I believe I hit all the points in your linked issue.
=> Expand the basics section

include/boost/decimal/detail/comparison.hpp, test/Jamfile, test/github_issue_799.cpp
=> Fix narrowing in equality of mixed types

include/boost/decimal/detail/mul_impl.hpp, test/Jamfile, test/github_issue_802.cpp
=> Fix calculation of resultant digits to keep us in the range of `uint128`

doc/decimal/cstdio.adoc, include/boost/decimal/cstdio.hpp, include/boost/decimal/detail/type_traits.hpp
=> Remove `sprintf` and fix conceptual requirements for <cstdio>

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/comparison.hpp, test/random_decimal128_comp.cpp, test/random_decimal128_fast_comp.cpp, test/random_decimal32_comp.cpp, test/random_decimal32_fast_comp.cpp, test/random_decimal64_comp.cpp, test/random_decimal64_fast_comp.cpp
This is a property guaranteed by IEEE 754
Closes: #811
=> Make -0 = +0

include/boost/decimal/decimal128_fast.hpp, test/Jamfile, test/github_issue_805.cpp
=> Fix `decimal128_fast` `scalblnd` implementation 

include/boost/decimal/bid_conversion.hpp, include/boost/decimal/uint128.hpp, test/Jamfile, test/compile_tests/uint128.cpp, test/test_big_uints.cpp
=> Make `uint128` public since we return in a few places to the user

include/boost/decimal/detail/concepts.hpp, include/boost/decimal/format.hpp, test/test_format.cpp
=> Move concepts into detail namespace

include/boost/decimal/decimal32.hpp
=> Remove decimal32 bool constructor

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/type_traits.hpp
Also removes the bool constructors if they exists
Closes: #839
=> Use delegating constructor for Integers

doc/decimal/decimal128.adoc, doc/decimal/decimal128_fast.adoc, doc/decimal/decimal32.adoc, doc/decimal/decimal32_fast.adoc, doc/decimal/decimal64.adoc, doc/decimal/decimal64_fast.adoc
=> Document typedefs

include/boost/decimal/decimal32.hpp, include/boost/decimal/detail/mul_impl.hpp
There's no point in normalizing numbers prior to multiple since the operation will work regardless.
=> Faster 32-bit mul

include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/components.hpp, include/boost/decimal/detail/mul_impl.hpp
=> Add one-shot decoding for 64-bit types and improve mul

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/detail/components.hpp, include/boost/decimal/detail/mul_impl.hpp
Allows the value to be passed by const ref since it will be far too large to pass on the registers. Instead of digit counting the resulting value we can apply a heuristic to get it close to correct (which is all we need).
=> Improve d128 mul

include/boost/decimal/charconv.hpp, include/boost/decimal/cstdio.hpp, include/boost/decimal/detail/fast_float/compute_float80_128.hpp, include/boost/decimal/detail/mul_impl.hpp, test/Jamfile, test/test_fast_float.cpp, test/test_snprintf.cpp, test/test_to_chars.cpp
This was the code path with the most missing lines of coverage. Many of them were already tested but optimized away since everything is `constexpr`
=> Improve Charconv coverage

include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, test/Jamfile, test/github_issue_798.cpp, test/github_issue_808.cpp
The values were often and incorrectly being set to infinity instead of zero. Also fixes the include guard for decimal128_fast since the IDE warned me about it.
Closes: #808
=> Fix division near 0

include/boost/decimal/detail/cmath/frexp10.hpp
Removes digit counting in the fast type case, and makes comparison to zero against an integer instead of a decimal type.
=> Small optimizations for frexp10

.drone.jsonnet, examples/adl.cpp, examples/basic_construction.cpp, include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp, include/boost/decimal/detail/cmath/acos.hpp, include/boost/decimal/detail/cmath/erf.hpp, include/boost/decimal/detail/cmath/floor.hpp, include/boost/decimal/detail/cmath/riemann_zeta.hpp, include/boost/decimal/detail/concepts.hpp, test/random_decimal128_comp.cpp, test/random_decimal128_fast_comp.cpp, test/random_decimal32_comp.cpp, test/random_decimal32_fast_comp.cpp, test/random_decimal64_comp.cpp, test/random_decimal64_fast_comp.cpp, test/test_cmath.cpp, test/test_decimal32_fast_basis.cpp, test/test_decimal64_fast_basis.cpp, test/test_float_conversion.cpp, test/test_format.cpp, test/test_git_issue_266.cpp, test/test_to_chars.cpp, test/test_to_string.cpp
You can either pass a signed integer, or a sign but not both. Should make things easier to reason about
Closes: #837
=> Add additional constraints to the constructors

include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/detail/buffer_sizing.hpp
Hi Matt (@mborland) this PR handles some warnings that I believe pointed out some unclear code. I detected these when doing local bare-metal benchmarking of the newer, faster `decimal64_t`. I ran into some (I believe) legitimate warnings on the metal and handled them.
The results of the benchmark are excellent and `decimal64_t` is better than two-fold faster than last year.
The table number was $490{\mu}s$ last year and is now $200{\mu}s$.
These are the updated numbers from boost::decimal Git-hash 0b474bf05f339f21d87dd1902dc6294bb9914254.
| Type                           |  runtime ${\mu}s$ |  relative  |    code-size [kb] |
|--------------------------------|---------------|------------|-------------------|
| 64-bit `double` (built-in, no FPU)      |  $22$          |   $1.0$      | …
=> Handle unclear code from local metal benching

doc/modules/ROOT/pages/benchmarks.adoc, test/benchmark_libbid.c, test/benchmark_libdfp.c
Gets most of the intel benchmarks. The mul for dec128 and all div are segfaulting for some inexplicable reason. Maybe the global error flag?
Closes: #933 
Closes: #807
=> Update Linux Benchmarks and Add Intel Benchmarks

doc/modules/ROOT/pages/cmath.adoc, include/boost/decimal/cmath.hpp, include/boost/decimal/detail/cmath/normalize.hpp, test/Jamfile, test/test_normalize.cpp
Right now the user has `frexp10` to get the components of a normalized number, but no way to internally normalize that value. This gives that functionality to them.
Closes: #954
=> Add and document user facing normalization function

.github/workflows/ci.yml, doc/modules/ROOT/nav.adoc, doc/modules/ROOT/pages/api_reference.adoc, doc/modules/ROOT/pages/config.adoc, include/boost/decimal/detail/config.hpp, include/boost/decimal/fmt_format.hpp, include/boost/decimal/format.hpp, test/test_big_uints.cpp, test/test_decimal32_fast_stream.cpp, test/test_decimal32_stream.cpp, test/test_snprintf.cpp, test/test_strtod.cpp
=> Add user and automatic configuration macro to disable exceptions 

include/boost/decimal/fmt_format.hpp, include/boost/decimal/format.hpp, test/test_format.cpp, test/test_format_fmtlib.cpp
=> Fix `<format>` support for clang

include/boost/decimal/charconv.hpp, include/boost/decimal/decimal128.hpp, include/boost/decimal/decimal128_fast.hpp, include/boost/decimal/decimal32.hpp, include/boost/decimal/decimal32_fast.hpp, include/boost/decimal/decimal64.hpp, include/boost/decimal/decimal64_fast.hpp
Closes: #1009 
Provides up to 40% performance improvement (decimal_fast128_t) with non-zero improvements across the board
=> Implement fast path of no precision scientific formatting

include/boost/decimal/decimal32_t.hpp, include/boost/decimal/detail/div_impl.hpp, include/boost/decimal/detail/fenv_rounding.hpp, include/boost/decimal/detail/remove_trailing_zeros.hpp, test/Jamfile, test/github_issue_1026.cpp, test/random_decimal32_fast_math.cpp, test/random_decimal32_math.cpp, test/test_cosh.cpp, test/test_expm1.cpp, test/test_fenv.cpp, test/test_fixed_width_trunc.cpp, test/test_sinh.cpp, test/test_to_chars.cpp
=> Implement check for sticky bit to fix rounding for all types and implement for `decimal32_t`

.github/workflows/ci.yml
See: https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/
=> Remove deprecated macOS version

include/boost/decimal/decimal128_t.hpp, include/boost/decimal/decimal32_t.hpp, include/boost/decimal/decimal64_t.hpp, include/boost/decimal/decimal_fast128_t.hpp, include/boost/decimal/decimal_fast32_t.hpp, include/boost/decimal/decimal_fast64_t.hpp, include/boost/decimal/detail/bit_layouts.hpp, include/boost/decimal/detail/ryu/ryu_generic_128.hpp, test/github_issue_426.cpp, test/roundtrip_decimal128.cpp, test/roundtrip_decimal128_fast.cpp, test/roundtrip_decimal32.cpp, test/roundtrip_decimal32_fast.cpp, test/roundtrip_decimal64.cpp, test/test_acosh.cpp, test/test_asinh.cpp, test/test_atanh.cpp, test/test_cmath.cpp, test/test_decimal32_fast_basis.cpp, test/test_decimal64_fast_basis.cpp, test/test_edges_and_behave.cpp, test/test_erf.cpp, test/test_float_conversion.cpp, test/test_frexp_ldexp.cpp, test/test_lgamma.cpp, test/test_tgamma.cpp
Since this platform has an unsupported long double configuration we need to delete those constructors and conversion functions. Also fix the tests
=> Fix build on POWER10

include/boost/decimal/decimal128_t.hpp, include/boost/decimal/decimal32_t.hpp, include/boost/decimal/decimal64_t.hpp, include/boost/decimal/decimal_fast128_t.hpp, include/boost/decimal/decimal_fast32_t.hpp, include/boost/decimal/decimal_fast64_t.hpp, test/Jamfile, test/github_issue_1087.cpp
=> Improve message from disallowed 3 arg constructor
